name: lu7stats
version: '1.0-SNAPSHOT'
main: com.lu7stats.lu7stats.StatAnnouncements
author: 'Andrew Peacock'
description: Plugin that uses PlaceholderAPI to broadcast top stat messages every 15 minutes with the help of PlayerStats.
api-version: '1.20'

permissions:
  lu7stats.seebroadcasts:
    description: Permission to see stat message broadcasts
    default: true
  lu7stats.manualbroadcasts:
    description: Permission to manually trigger a broadcast
    default: false
  lu7stats.reload:
    description: Permission to manually trigger a broadcast
    default: false

commands:
  broadcaststat:
    description: Manually triggers the broadcast of a random stat message
    usage: /broadcaststat
    permission: lu7stats.manualbroadcasts
  lu7statsreload:
    description: Manually reload all plugin config files
    usage: /lu7statsreload
    permission: lu7stats.reload